Feat adjust mock
ice-lab/ice-scripts pull request #50
Opened 2019-08-26 02:43 UTC by daysai

feat: mock 支持 index.ts
feat: devMock 在 devServer 之前启动

2019-08-26 05:50 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +const configFile = existsSync(tsConfigFile) ? tsConfigFile : jsConfigFile;
使用 try {require.resolve('mock path');} catch (err) {} 是不是可以达到同样效果

2019-08-26 05:50 UTC, ClarkXia commented on packages/ice-scripts/package.json
> +    "webpack-dev-mock": "^0.1.3",
小版本迭代无需更新依赖

2019-08-27 04:06 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +const configFile = winPath(existsSync(tsConfigFile) ? tsConfigFile : jsConfigFile);
try { require.resolve('path')} catch(err) { log.error }

2019-08-27 04:12 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +      method: 'get',
['get', 'post', ...].map 是不是可以支持全部 method

2019-08-27 04:15 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +        multer().any()(req, res, () => {
添加下comment 这块比较难理解

2019-08-27 04:20 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +  const keys = [];
keys 里面存的是什么内容

2019-08-27 07:10 UTC, ClarkXia requested changes

2019-08-27 07:10 UTC, ClarkXia commented on packages/webpack-dev-mock/index.js
> +      const withPathFile = withPath(file);
withPath => winPath

2019-08-27 09:24 UTC, ClarkXia commented
changelog 补充下

2019-08-27 10:53 UTC, ClarkXia approved these changes

2019-08-27 10:57 UTC, daysai commented on packages/webpack-dev-mock/index.js
> +      const withPathFile = withPath(file);
done

2019-08-27 10:58 UTC, daysai commented on packages/webpack-dev-mock/index.js
> +  const keys = [];
调整为 轮训时 获取

2019-08-27 10:58 UTC, daysai commented on packages/webpack-dev-mock/index.js
> +        multer().any()(req, res, () => {
done

2019-08-27 10:58 UTC, daysai commented on packages/webpack-dev-mock/index.js
> +      method: 'get',
done

2019-08-27 11:56 UTC, merged