Support cache-loader in ice-scripts
ice-lab/ice-scripts pull request #51
Opened 2019-08-26 03:23 UTC by tanhengyeow

Fixes [alibaba/ice#2753](https://github.com/alibaba/ice/issues/2753).

2019-08-26 03:26 UTC, ClarkXia requested changes

2019-08-26 03:26 UTC, ClarkXia commented on packages/ice-plugin-cache-loader/index.js
> +        confRule.uses.clear();
为什么需要清空 uses ？

2019-08-26 03:28 UTC, ClarkXia commented on packages/ice-plugin-cache-loader/package.json
> +    "webpack": "^4.39.2"
这个插件可以不用关心 webpack

2019-08-29 02:23 UTC, ClarkXia commented on packages/ice-plugin-cache-loader/index.js
> +              .before(ruleName);
before 对应的应该是 use 的名称，比如 babel-loader https://github.com/ice-lab/ice-scripts/blob/cffa95f328555dbb2fe5ad8d32750dbba64c7c5e/packages/ice-scripts/lib/config/setWebpackLoaders.js#L109

2019-08-29 02:23 UTC, ClarkXia commented on packages/ice-plugin-cache-loader/index.js
> +              .loader('cache-loader')
.loader(require.resolve('cache-loader'))

2019-08-29 08:03 UTC, tanhengyeow commented on packages/ice-plugin-cache-loader/index.js
> +              .before(ruleName);
Left a comment on how `.before(ruleName);` works!

2019-08-29 08:04 UTC, tanhengyeow commented on packages/ice-plugin-cache-loader/index.js
> +              .before(ruleName);
Left a comment on how `.before(ruleName)` works!

2019-08-29 12:44 UTC, ClarkXia commented on packages/ice-plugin-cache-loader/index.js
> +/* eslint-disable no-underscore-dangle */
尽量不使用文件级别的 eslint-disable，在具体的位置进行注明

2019-08-29 12:44 UTC, ClarkXia commented
补充下 README 和 CHANGELOG

2019-09-16 03:25 UTC, ClarkXia approved these changes

2019-09-16 03:25 UTC, merged