feat: add ice-plugin-fusion-material
ice-lab/ice-scripts pull request #69
Opened 2019-11-01 06:34 UTC by skysuka

2019-11-01 06:45 UTC, ClarkXia requested changes

2019-11-01 06:45 UTC, ClarkXia commented on packages/ice-plugin-fusion-material/index.js
> +        if (pkg.blockConfig && pkg.blockConfig.views) {
区块和模版处理逻辑基本类似，可以进行一定的抽象，建议优化下代码

2019-11-01 06:45 UTC, ClarkXia commented on packages/ice-plugin-fusion-material/index.js
> +  await page.setContent(htmlContent); // load the local html file
注释风格尽量使用换行来保持风格一致

2019-11-01 06:46 UTC, ClarkXia commented
lint 问题修复下

2019-11-04 03:16 UTC, ClarkXia requested changes

2019-11-04 03:16 UTC, ClarkXia commented on package.json
> +    "puppeteer": "^2.0.0"
在具体的插件中依赖即可

2019-11-04 05:52 UTC, imsobear commented
1. MR 描述下干了什么
2. puppter 的依赖建议参考下（或者直接使用） ，每次都下载体验很差：https://github.com/alibaba/ice/tree/master/packages/ice-screenshot
3. 插件命名有点奇怪，建议先具体的表达出来这个插件是做什么的，然后对照起个名字

2019-11-05 08:04 UTC, skysuka commented on package.json
> +    "puppeteer": "^2.0.0"
已根据https://github.com/alibaba/ice/tree/master/packages/ice-screenshot修改

2019-11-05 08:04 UTC, skysuka commented
> 1. MR 描述下干了什么
> 2. puppter 的依赖建议参考下（或者直接使用） ，每次都下载体验很差：https://github.com/alibaba/ice/tree/master/packages/ice-screenshot
> 3. 插件命名有点奇怪，建议先具体的表达出来这个插件是做什么的，然后对照起个名字

2019-11-05 08:23 UTC, skysuka commented
@imsobear 
已根据https://github.com/alibaba/ice/tree/master/packages/ice-screenshot修改puppeteer

2019-11-05 08:57 UTC, skysuka commented on packages/ice-plugin-fusion-material/index.js
> +        if (pkg.blockConfig && pkg.blockConfig.views) {
好的

2019-11-05 10:14 UTC, ClarkXia requested changes

2019-11-05 10:14 UTC, ClarkXia commented on package.json
> +    "puppeteer": "^2.0.0"
外层 package.json 中不应该依赖 puppeteer

2019-11-05 10:14 UTC, ClarkXia commented on packages/ice-plugin-fusion-material/index.js
> +  console.log('htmls', htmls);
调试代码建议删除，插件信息流建议统一通过 插件 api 的 log 方法输出

2019-11-05 10:14 UTC, ClarkXia commented on packages/ice-plugin-fusion-material/utils/createServer.js
> +const chalk = require('chalk');
chalk 依赖没有在 package.json 中出现

2019-11-05 10:16 UTC, ClarkXia requested changes

2019-11-05 10:16 UTC, ClarkXia commented on packages/ice-plugin-fusion-material/README.md
> +See [docs](https://github.com/alibaba/ice/blob/master/docs/cli/plugin-list/fusion-material.md).
readme 可以先描述清楚插件的功能和用法，后面再考虑迁移到文档中

2019-11-19 03:39 UTC, ClarkXia approved these changes

2019-11-19 03:40 UTC, merged